aws:
  region: "sa-east-1"

deploy:
  aws:
    dev:
      account: "403339561517"
      apigateway:
        apigatewayId: "olq0pyde45"
      loadBalancerDnsMain: "tech-challenge-lb-ab041078c8d35bb0.elb.sa-east-1.amazonaws.com:9000:8080"

infra:
  terraform:
    destroy: false