aws:
  region: "sa-east-1"

deploy:
  aws:
    dev:
      account: "403339561517"
      apigateway:
        apigatewayId: "olq0pyde45"
      loadBalancerDnsMain: "tech-challenge-lb-f602dac972c5f268.elb.sa-east-1.amazonaws.com:8080"

infra:
  terraform:
    destroy: false