openapi: 3.0.0
info:
  title: API G52 Tech Challenge
  description: |
    Test destroy resources
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.  
    Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

    ### Features

    - Fast and reliable
    - Secure endpoints
    - Easy integration

    ### Example Table

    | Method | Endpoint   | Description           |
    |--------|------------|-----------------------|
    | GET    | /hello     | Returns hello world   |
    | POST   | /goodbye   | Says goodbye         |

    > Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    >
    > Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Development

paths:
  /clientes:
    post:
      tags:
        - Clientes
      summary: Criar Cliente
      description: |
        Endpoint para criar um cliente
      operationId: post/clientes
      parameters:
        - $ref: "#/components/parameters/x_correlationid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateClienteRequest"
            examples:
              CreateClienteRequest:
                $ref: "#/components/examples/CreateClienteRequest"
      responses:
        "201":
          description: Cliente criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateClienteResponse"
              examples:
                CreateClienteResponse:
                  $ref: "#/components/examples/CreateClienteResponse"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
        "503":
          $ref: "#/components/responses/503"
      #      security:
      #        - APIGatewaySTSAuthorizer:
      #            - none
      x-amazon-apigateway-integration:
        timeoutInMillis: 14000
        type: "http_proxy"
        httpMethod: "POST"
        #        credentials: "arn:aws:iam::${pipes_deploy_aws_env_account}:role/iamsr/role-gateway-invoke-authorizer"
        uri: "http://${loadBalancerDnsMain}/clientes"
        responses:
          default:
            statusCode: "503"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        connectionId: "${vpclink}"
        requestParameters:
          integration.request.header.x-correlationid: "method.request.header.x-correlationid"
      x-amazon-apigateway-request-validator: params-only
    get:
      tags:
        - Clientes
      summary: Listar Clientes
      description: |
        Endpoint para listar de cliente por clienteId
      operationId: get/clientes
      parameters:
        - $ref: "#/components/parameters/x_correlationid"
        - name: page
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Número de clientes por página
          required: false
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: Clientes listados
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListClientesResponse"
              examples:
                ListClientesResponse:
                  $ref: "#/components/examples/ListClientesResponse"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
        "503":
          $ref: "#/components/responses/503"
      #      security:
      #        - APIGatewaySTSAuthorizer:
      #            - none
      x-amazon-apigateway-integration:
        timeoutInMillis: 14000
        type: "http_proxy"
        httpMethod: "GET"
        #        credentials: "arn:aws:iam::${pipes_deploy_aws_env_account}:role/iamsr/role-gateway-invoke-authorizer"
        uri: "http://${loadBalancerDnsMain}/clientes"
        responses:
          default:
            statusCode: "503"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        connectionId: "${vpclink}"
        requestParameters:
          integration.request.querystring.page: "method.request.querystring.page"
          integration.request.querystring.size: "method.request.querystring.size"
          integration.request.header.x-correlationid: "method.request.header.x-correlationid"
      x-amazon-apigateway-request-validator: params-only
  /clientes/{clienteId}:
    put:
      tags:
        - Clientes
      summary: Atualizar Cliente
      description: |
        Endpoint para atualizar um cliente
      operationId: put/clientes/{clienteId}
      parameters:
        - $ref: "#/components/parameters/x_correlationid"
        - name: clienteId
          in: path
          description: Identificador do cliente
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateClienteRequest"
            examples:
              UpdateClienteRequest:
                $ref: "#/components/examples/UpdateClienteRequest"
      responses:
        "200":
          description: Cliente atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateClienteResponse"
              examples:
                UpdateClienteResponse:
                  $ref: "#/components/examples/UpdateClienteResponse"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
        "503":
          $ref: "#/components/responses/503"
      #      security:
      #        - APIGatewaySTSAuthorizer:
      #            - none
      x-amazon-apigateway-integration:
        timeoutInMillis: 14000
        type: "http_proxy"
        httpMethod: "PUT"
        #        credentials: "arn:aws:iam::${pipes_deploy_aws_env_account}:role/iamsr/role-gateway-invoke-authorizer"
        uri: "http://${loadBalancerDnsMain}/clientes/{clienteId}"
        responses:
          default:
            statusCode: "503"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        connectionId: "${vpclink}"
        requestParameters:
          integration.request.path.clienteId: "method.request.path.clienteId"
          integration.request.header.x-correlationid: "method.request.header.x-correlationid"
      x-amazon-apigateway-request-validator: params-only
    get:
      tags:
        - Clientes
      summary: Consultar Cliente
      description: |
        Endpoint para consulta de cliente por clienteId
      operationId: get/clientes/{clienteId}
      parameters:
        - $ref: "#/components/parameters/x_correlationid"
        - name: clienteId
          in: path
          description: Identificador do cliente
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: Cliente consultado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FindClienteResponse"
              examples:
                FindClienteResponse:
                  $ref: "#/components/examples/FindClienteResponse"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
        "503":
          $ref: "#/components/responses/503"
      #      security:
      #        - APIGatewaySTSAuthorizer:
      #            - none
      x-amazon-apigateway-integration:
        timeoutInMillis: 14000
        type: "http_proxy"
        httpMethod: "GET"
        #        credentials: "arn:aws:iam::${pipes_deploy_aws_env_account}:role/iamsr/role-gateway-invoke-authorizer"
        uri: "http://${loadBalancerDnsMain}/clientes/{clienteId}"
        responses:
          default:
            statusCode: "503"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        connectionId: "${vpclink}"
        requestParameters:
          integration.request.path.clienteId: "method.request.path.clienteId"
          integration.request.header.x-correlationid: "method.request.header.x-correlationid"
      x-amazon-apigateway-request-validator: params-only
    delete:
      tags:
        - Clientes
      summary: Deletar Cliente
      description: |
        Endpoint para deleção de cliente por clienteId
      operationId: delete/clientes/{clienteId}
      parameters:
        - $ref: "#/components/parameters/x_correlationid"
        - name: clienteId
          in: path
          description: Identificador do cliente
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "405":
          $ref: "#/components/responses/405"
        "500":
          $ref: "#/components/responses/500"
        "503":
          $ref: "#/components/responses/503"
      #      security:
      #        - APIGatewaySTSAuthorizer:
      #            - none
      x-amazon-apigateway-integration:
        timeoutInMillis: 14000
        type: "http_proxy"
        httpMethod: "DELETE"
        #        credentials: "arn:aws:iam::${pipes_deploy_aws_env_account}:role/iamsr/role-gateway-invoke-authorizer"
        uri: "http://${loadBalancerDnsMain}/clientes/{clienteId}"
        responses:
          default:
            statusCode: "503"
        passthroughBehavior: "when_no_match"
        connectionType: "VPC_LINK"
        connectionId: "${vpclink}"
        requestParameters:
          integration.request.path.clienteId: "method.request.path.clienteId"
          integration.request.header.x-correlationid: "method.request.header.x-correlationid"
      x-amazon-apigateway-request-validator: params-only
#  /hello:
#    get:
#      tags:
#        - Hello World
#      summary: Consulta Hello World
#      description: |
#        Endpoint para consultar hello world
#      operationId: get/hello
#      parameters:
#        - $ref: "#/components/parameters/x_correlationid"
#      responses:
#        "200":
#          description: Responde hello world
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/HelloWorldResponse"
#              examples:
#                HelloWorldResponse:
#                  $ref: "#/components/examples/HelloWorldResponse"
#        "400":
#          $ref: "#/components/responses/400"
#        "401":
#          $ref: "#/components/responses/401"
#        "403":
#          $ref: "#/components/responses/403"
#        "405":
#          $ref: "#/components/responses/405"
#        "500":
#          $ref: "#/components/responses/500"
#        "503":
#          $ref: "#/components/responses/503"
##      security:
##        - APIGatewaySTSAuthorizer:
##            - none
#      x-amazon-apigateway-integration:
#        timeoutInMillis: 14000
#        type: "http_proxy"
#        httpMethod: "GET"
##        credentials: "arn:aws:iam::${pipes_deploy_aws_env_account}:role/iamsr/role-gateway-invoke-authorizer"
#        uri: "http://${loadBalancerDnsMain}/hello"
#        responses:
#          default:
#            statusCode: "503"
#        passthroughBehavior: "when_no_match"
#        connectionType: "VPC_LINK"
#        connectionId: "${vpclink}"
#        requestParameters:
#          integration.request.header.x-correlationid: "method.request.header.x-correlationid"
#      x-amazon-apigateway-request-validator: params-only

components:
  parameters:
    x_correlationid:
      $ref: ./parameters/x_correlationid.yaml
  schemas:
    FindClienteResponse:
      $ref: ./schemas/FindClienteResponse.yaml
    CreateClienteRequest:
      $ref: ./schemas/CreateClienteRequest.yaml
    CreateClienteResponse:
      $ref: ./schemas/CreateClienteResponse.yaml
    UpdateClienteRequest:
      $ref: ./schemas/UpdateClienteRequest.yaml
    UpdateClienteResponse:
      $ref: ./schemas/UpdateClienteResponse.yaml
    ListClientesResponse:
      $ref: ./schemas/ListClientesResponse.yaml
#    HelloWorldResponse:
#      $ref: ./schemas/HelloWorldResponse.yaml
  examples:
    FindClienteResponse:
      $ref: ./examples/200FindClienteResponse.yaml
    CreateClienteRequest:
      $ref: ./examples/requests/CreateClienteRequest.yaml
    CreateClienteResponse:
      $ref: ./examples/201CreateClienteResponse.yaml
    UpdateClienteRequest:
      $ref: ./examples/requests/UpdateClienteRequest.yaml
    UpdateClienteResponse:
      $ref: ./examples/200UpdateClienteResponse.yaml
    ListClientesResponse:
      $ref: ./examples/200ListClienteResponse.yaml
      yaml:
  #    HelloWorldResponse:
#      $ref: ./examples/200HelloWorldResponse.yaml
  responses:
    '204':
      $ref: ./responses/204.yaml
    '400':
      $ref: ./responses/400.yaml
    '401':
      $ref: ./responses/401.yaml
    '403':
      $ref: ./responses/403.yaml
    '404':
      $ref: ./responses/404.yaml
    '405':
      $ref: ./responses/405.yaml
    '422':
      $ref: ./responses/422.yaml
    '500':
      $ref: ./responses/500.yaml
    '503':
      $ref: ./responses/503.yaml
    '504':
      $ref: ./responses/504.yaml

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
x-amazon-apigateway-gateway-responses:
  UNAUTHORIZED:
    statusCode: 401
    responseTemplates:
      application/json: "{\n \"message\": \"Expired Token\" \n }"
DEFAULT_5XX:
  statusCode: 503
  responseTemplates:
    application/json: "{\n \"message\": \"Sorry, for broke student reasons the servers are scheduled to operate only between 2pm and 8pm\",\n \"exceptionType\": \"Service Unavailable\" \n }"
x-amazon-apigateway-policy:
  Version: 2012-10-17
  Statement:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource: "*"